# Generated by Django 4.2 on 2024-05-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cellphone',
            field=models.CharField(max_length=10),
        ),
    ]
