# Generated by Django 4.2 on 2024-05-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_cellphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.client')),
                ('email', models.BooleanField()),
                ('sms', models.BooleanField()),
            ],
            options={
                'verbose_name': 'notification_preferences',
                'verbose_name_plural': 'notification_preferences',
                'db_table': 'notification_preferences',
            },
        ),
    ]
