# Generated by Django 4.2 on 2024-05-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferences',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='sms',
            field=models.BooleanField(default=False),
        ),
    ]
